-- ============================================================
-- AfriMoney Intelligence Platform
-- Bronze Layer DDL — Raw immutable tables
-- Step 2 of 6: Run as AFRIMONEY_ENG using AFRIMONEY_INGEST_WH
-- ============================================================

USE ROLE AFRIMONEY_ENG;
USE WAREHOUSE AFRIMONEY_INGEST_WH;
USE DATABASE AFRIMONEY_DB;
USE SCHEMA BRONZE;

-- All Bronze tables use CLUSTER BY on date fields for scan efficiency.
-- DATA_RETENTION_TIME_IN_DAYS = 90 for cost-efficient time-travel.
-- COPY INTO commands follow each table definition.

-- ── DIM_BUSINESS ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS DIM_BUSINESS (
    BUSINESS_SK          NUMBER AUTOINCREMENT PRIMARY KEY,
    BUSINESS_KEY         VARCHAR(10)  NOT NULL UNIQUE,
    BUSINESS_NAME        VARCHAR(100) NOT NULL,
    FOUNDED_YEAR         NUMBER(4),
    HQ_COUNTRY           VARCHAR(5),
    PRIMARY_CURRENCY     VARCHAR(5),
    BRAND_COLOUR         VARCHAR(10),
    _LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE              VARCHAR(50)   DEFAULT 'CSV_BOOTSTRAP'
)
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = 'Business/brand master: MKR=Mukuru, MMY=Mama Money';

-- ── DIM_CUSTOMER (SCD Type 2) ─────────────────────────────────
CREATE TABLE IF NOT EXISTS DIM_CUSTOMER (
    CUSTOMER_SK              NUMBER AUTOINCREMENT PRIMARY KEY,
    CUSTOMER_ID              VARCHAR(20)  NOT NULL,
    BUSINESS_KEY             VARCHAR(10)  NOT NULL,
    FIRST_NAME               VARCHAR(100),
    LAST_NAME                VARCHAR(100),
    DATE_OF_BIRTH            DATE,
    AGE_YEARS                NUMBER(3),
    GENDER                   VARCHAR(5),
    NATIONALITY              VARCHAR(5),
    RESIDENCE_COUNTRY        VARCHAR(5),
    PREFERRED_LANGUAGE       VARCHAR(5),
    MOBILE_NUMBER_TOKEN      VARCHAR(50),   -- tokenised, never plaintext
    EMAIL_HASH               VARCHAR(64),   -- SHA-256
    REGISTRATION_DATETIME    TIMESTAMP_NTZ,
    REGISTRATION_CHANNEL     VARCHAR(30),
    KYC_LEVEL                VARCHAR(20),
    KYC_COMPLETED_DATE       DATE,
    CUSTOMER_STATUS          VARCHAR(20),
    RISK_BAND                VARCHAR(20),
    CUSTOMER_SEGMENT         VARCHAR(20),
    MONTHLY_INCOME_BAND      VARCHAR(20),
    EMPLOYER_TYPE            VARCHAR(30),
    HAS_SA_ID                BOOLEAN,
    HAS_PASSPORT             BOOLEAN,
    IS_MARKETING_OPT_IN      BOOLEAN,
    ACQUISITION_SOURCE       VARCHAR(30),
    -- SCD2 fields
    SCD_VERSION              NUMBER(3)     DEFAULT 1,
    SCD_START_DATE           DATE          NOT NULL,
    SCD_END_DATE             DATE,
    IS_CURRENT               BOOLEAN       DEFAULT TRUE,
    _LOADED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    _SOURCE                  VARCHAR(50)   DEFAULT 'CSV_BOOTSTRAP'
)
CLUSTER BY (BUSINESS_KEY, SCD_START_DATE)
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = 'Customer SCD Type 2 — PII tokenised/hashed; raw IDs never stored here';

-- ── DIM_RECIPIENT ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS DIM_RECIPIENT (
    RECIPIENT_SK             NUMBER AUTOINCREMENT PRIMARY KEY,
    RECIPIENT_ID             VARCHAR(20)  NOT NULL UNIQUE,
    SENDER_CUSTOMER_ID       VARCHAR(20)  NOT NULL,
    BUSINESS_KEY             VARCHAR(10),
    FIRST_NAME               VARCHAR(100),
    LAST_NAME                VARCHAR(100),
    RELATIONSHIP             VARCHAR(30),
    RECEIVE_COUNTRY          VARCHAR(5),
    PREFERRED_PAYOUT_METHOD  VARCHAR(30),
    MOBILE_TOKEN             VARCHAR(50),
    BANK_ACCOUNT_TOKEN       VARCHAR(50),
    WALLET_TOKEN             VARCHAR(50),
    IS_VERIFIED              BOOLEAN,
    CREATED_DATE             DATE,
    TRANSFER_COUNT           NUMBER(6)    DEFAULT 0,
    _LOADED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (RECEIVE_COUNTRY)
DATA_RETENTION_TIME_IN_DAYS = 90;

-- ── DIM_CORRIDOR ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS DIM_CORRIDOR (
    CORRIDOR_SK      NUMBER AUTOINCREMENT PRIMARY KEY,
    CORRIDOR_CODE    VARCHAR(10) NOT NULL UNIQUE,
    SEND_COUNTRY     VARCHAR(5),
    RECEIVE_COUNTRY  VARCHAR(5),
    SEND_CURRENCY    VARCHAR(5),
    RECEIVE_CURRENCY VARCHAR(5),
    TRADE_BLOC       VARCHAR(20),
    MUKURU_ACTIVE    BOOLEAN,
    MAMA_MONEY_ACTIVE BOOLEAN,
    IS_HIGH_VOLUME   BOOLEAN,
    REGULATORY_RISK  VARCHAR(10),
    _LOADED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ── DIM_DATE ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS DIM_DATE (
    DATE_SK         NUMBER PRIMARY KEY,
    FULL_DATE       DATE    NOT NULL UNIQUE,
    YEAR            NUMBER(4),
    QUARTER         NUMBER(1),
    MONTH           NUMBER(2),
    MONTH_NAME      VARCHAR(15),
    WEEK_OF_YEAR    NUMBER(2),
    DAY_OF_WEEK     NUMBER(1),
    DAY_NAME        VARCHAR(15),
    DAY_OF_MONTH    NUMBER(2),
    IS_WEEKEND      BOOLEAN,
    IS_MONTH_END    BOOLEAN,
    IS_QUARTER_END  BOOLEAN,
    FISCAL_YEAR     NUMBER(4),
    FISCAL_QUARTER  NUMBER(1)
)
COMMENT = 'Static date spine 2021-2026; no _LOADED_AT needed';

-- ── FACT_REMITTANCE_TRANSFER ───────────────────────────────────
CREATE TABLE IF NOT EXISTS FACT_REMITTANCE_TRANSFER (
    TRANSFER_ID              VARCHAR(20)   NOT NULL PRIMARY KEY,
    TRANSFER_REFERENCE       VARCHAR(30),
    BUSINESS_KEY             VARCHAR(10)   NOT NULL,
    SENDER_CUSTOMER_ID       VARCHAR(20)   NOT NULL,
    RECIPIENT_ID             VARCHAR(20),
    CORRIDOR_CODE            VARCHAR(10),
    SEND_COUNTRY             VARCHAR(5),
    RECEIVE_COUNTRY          VARCHAR(5),
    SEND_CURRENCY            VARCHAR(5),
    RECEIVE_CURRENCY         VARCHAR(5),
    CHANNEL                  VARCHAR(30),
    PAYMENT_METHOD           VARCHAR(30),
    PAYOUT_METHOD            VARCHAR(30),
    CREATED_DATETIME         TIMESTAMP_NTZ,
    CREATED_DATE_KEY         NUMBER,
    COMPLETED_DATETIME       TIMESTAMP_NTZ,
    COMPLETED_DATE_KEY       NUMBER,
    TRANSFER_STATUS          VARCHAR(30),
    -- Monetary amounts (all ZAR reporting currency)
    SEND_AMOUNT_ZAR          NUMBER(14,2),
    RECEIVE_AMOUNT           NUMBER(14,2),
    TRANSFER_FEE_ZAR         NUMBER(12,2),
    VAT_ZAR                  NUMBER(12,2),
    FX_MARGIN_ZAR            NUMBER(12,2),
    PARTNER_COST_ZAR         NUMBER(12,2),
    GROSS_REVENUE_ZAR        NUMBER(12,2),
    NET_REVENUE_ZAR          NUMBER(12,2),
    -- FX
    MARKET_FX_RATE           NUMBER(18,6),
    CUSTOMER_FX_RATE         NUMBER(18,6),
    FX_SPREAD_PCT            NUMBER(8,4),
    -- Operational
    PAYMENT_ATTEMPTS         NUMBER(2),
    PAYOUT_ATTEMPTS          NUMBER(2),
    COMPLETION_MINUTES       NUMBER(8),
    -- Flags
    IS_COMPLETED             BOOLEAN,
    IS_FAILED                BOOLEAN,
    IS_CANCELLED             BOOLEAN,
    IS_REFUNDED              BOOLEAN,
    IS_FIRST_TRANSFER        BOOLEAN,
    IS_REPEAT_CUSTOMER       BOOLEAN,
    IS_SUSPECTED_FRAUD       BOOLEAN,
    _LOADED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (BUSINESS_KEY, TO_DATE(CREATED_DATETIME))
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = 'Grain: one remittance order. Do not combine with FACT_PAYMENT or FACT_PAYOUT.';

-- ── FACT_TRANSFER_STATUS_HISTORY ──────────────────────────────
CREATE TABLE IF NOT EXISTS FACT_TRANSFER_STATUS_HISTORY (
    STATUS_HISTORY_ID         NUMBER AUTOINCREMENT PRIMARY KEY,
    TRANSFER_ID               VARCHAR(20) NOT NULL,
    BUSINESS_KEY              VARCHAR(10),
    STATUS_CODE               VARCHAR(40),
    STATUS_DATETIME           TIMESTAMP_NTZ,
    DATE_KEY                  NUMBER,
    ELAPSED_MINUTES_FROM_CREATED NUMBER(8),
    SYSTEM_USER               VARCHAR(20),
    NOTES                     VARCHAR(500),
    _LOADED_AT                TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (BUSINESS_KEY, TO_DATE(STATUS_DATETIME));

-- ── FACT_PAYMENT ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS FACT_PAYMENT (
    PAYMENT_ID               VARCHAR(20)  NOT NULL PRIMARY KEY,
    TRANSFER_ID              VARCHAR(20)  NOT NULL,
    BUSINESS_KEY             VARCHAR(10),
    SENDER_CUSTOMER_ID       VARCHAR(20),
    PAYMENT_METHOD           VARCHAR(30),
    PAYMENT_DATETIME         TIMESTAMP_NTZ,
    DATE_KEY                 NUMBER,
    AMOUNT_ZAR               NUMBER(14,2),
    FEE_ZAR                  NUMBER(12,2),
    TOTAL_CHARGED_ZAR        NUMBER(14,2),
    ATTEMPT_NUMBER           NUMBER(2),
    PAYMENT_STATUS           VARCHAR(20),
    DECLINE_REASON           VARCHAR(50),
    PAYMENT_REFERENCE        VARCHAR(40),
    GATEWAY_CODE             VARCHAR(20),
    _LOADED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (BUSINESS_KEY, TO_DATE(PAYMENT_DATETIME));

-- ── FACT_PAYOUT ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS FACT_PAYOUT (
    PAYOUT_ID                VARCHAR(20)  NOT NULL PRIMARY KEY,
    TRANSFER_ID              VARCHAR(20)  NOT NULL,
    BUSINESS_KEY             VARCHAR(10),
    RECIPIENT_ID             VARCHAR(20),
    RECEIVE_COUNTRY          VARCHAR(5),
    PAYOUT_METHOD            VARCHAR(30),
    PAYOUT_DATETIME          TIMESTAMP_NTZ,
    DATE_KEY                 NUMBER,
    AMOUNT_RECEIVE_CURRENCY  NUMBER(14,2),
    AMOUNT_ZAR_EQUIVALENT    NUMBER(14,2),
    PARTNER_CODE             VARCHAR(20),
    PARTNER_LOCATION_ID      VARCHAR(20),
    ATTEMPT_NUMBER           NUMBER(2),
    PAYOUT_STATUS            VARCHAR(20),
    FAILURE_REASON           VARCHAR(50),
    COLLECTION_CODE          VARCHAR(20),
    COLLECTED_DATETIME       TIMESTAMP_NTZ,
    _LOADED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (BUSINESS_KEY, RECEIVE_COUNTRY, TO_DATE(PAYOUT_DATETIME));

-- ── FACT_FX_RATE ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS FACT_FX_RATE (
    FX_RATE_ID      NUMBER       NOT NULL PRIMARY KEY,
    CORRIDOR_CODE   VARCHAR(10),
    SEND_CURRENCY   VARCHAR(5),
    RECEIVE_CURRENCY VARCHAR(5),
    RATE_DATETIME   TIMESTAMP_NTZ,
    DATE_KEY        NUMBER,
    MARKET_RATE     NUMBER(18,6),
    CUSTOMER_RATE   NUMBER(18,6),
    FX_SPREAD_PCT   NUMBER(8,4),
    MARGIN_PER_UNIT NUMBER(18,6),
    RATE_SOURCE     VARCHAR(20),
    IS_ACTIVE       BOOLEAN,
    _LOADED_AT      TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (CORRIDOR_CODE, TO_DATE(RATE_DATETIME));

-- ── FACT_WALLET_LEDGER ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS FACT_WALLET_LEDGER (
    LEDGER_ID           VARCHAR(20)  NOT NULL PRIMARY KEY,
    WALLET_ID           VARCHAR(20),
    CUSTOMER_ID         VARCHAR(20),
    BUSINESS_KEY        VARCHAR(10),
    ENTRY_TYPE          VARCHAR(30),
    ENTRY_DIRECTION     VARCHAR(10),
    AMOUNT_ZAR          NUMBER(14,2),
    RUNNING_BALANCE_ZAR NUMBER(14,2),
    ENTRY_DATETIME      TIMESTAMP_NTZ,
    DATE_KEY            NUMBER,
    REFERENCE_ID        VARCHAR(20),
    CHANNEL             VARCHAR(30),
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (BUSINESS_KEY, TO_DATE(ENTRY_DATETIME));

-- ── FACT_CARD_TRANSACTION ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS FACT_CARD_TRANSACTION (
    CARD_TXN_ID          VARCHAR(20)  NOT NULL PRIMARY KEY,
    CARD_ACCOUNT_ID      VARCHAR(20),
    CUSTOMER_ID          VARCHAR(20)  NOT NULL,
    BUSINESS_KEY         VARCHAR(10),
    CARD_TYPE            VARCHAR(30),
    MERCHANT_CATEGORY    VARCHAR(30),
    MERCHANT_NAME        VARCHAR(50),
    MERCHANT_COUNTRY     VARCHAR(5),
    TRANSACTION_DATETIME TIMESTAMP_NTZ,
    DATE_KEY             NUMBER,
    AMOUNT_ZAR           NUMBER(12,2),
    TRANSACTION_TYPE     VARCHAR(30),
    CHANNEL              VARCHAR(20),
    AUTHORISATION_CODE   VARCHAR(20),
    TRANSACTION_STATUS   VARCHAR(20),
    DECLINE_REASON       VARCHAR(50),
    IS_FRAUD_FLAGGED     BOOLEAN,
    _LOADED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (BUSINESS_KEY, MERCHANT_CATEGORY, TO_DATE(TRANSACTION_DATETIME));

-- ── MUKURU EXTENSIONS ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS FACT_LOAN_APPLICATION (
    LOAN_ID                    VARCHAR(20) NOT NULL PRIMARY KEY,
    CUSTOMER_ID                VARCHAR(20),
    BUSINESS_KEY               VARCHAR(10),
    APPLICATION_DATETIME       TIMESTAMP_NTZ,
    DATE_KEY                   NUMBER,
    DECISION                   VARCHAR(20),
    LOAN_PURPOSE               VARCHAR(30),
    PRINCIPAL_ZAR              NUMBER(12,2),
    INTEREST_RATE_ANNUAL_PCT   NUMBER(6,2),
    TERM_MONTHS                NUMBER(2),
    MONTHLY_PAYMENT_ZAR        NUMBER(12,2),
    TOTAL_REPAYABLE_ZAR        NUMBER(14,2),
    DISBURSEMENT_METHOD        VARCHAR(30),
    LOAN_STATUS                VARCHAR(20),
    PROBABILITY_OF_DEFAULT     NUMBER(8,4),
    EXPECTED_CREDIT_LOSS_ZAR   NUMBER(12,2),
    DAYS_PAST_DUE              NUMBER(4),
    CARD_ACCOUNT_AGE_DAYS      NUMBER(6),
    AVG_MONTHLY_CARD_SPEND_ZAR NUMBER(12,2),
    SALARY_INDICATOR           BOOLEAN,
    PREVIOUS_LOANS             NUMBER(3),
    PREVIOUS_LOANS_REPAID      NUMBER(3),
    _LOADED_AT                 TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (DECISION, TO_DATE(APPLICATION_DATETIME));

CREATE TABLE IF NOT EXISTS FACT_LOAN_REPAYMENT (
    REPAYMENT_ID       VARCHAR(20) NOT NULL PRIMARY KEY,
    LOAN_ID            VARCHAR(20),
    CUSTOMER_ID        VARCHAR(20),
    BUSINESS_KEY       VARCHAR(10),
    INSTALMENT_NUMBER  NUMBER(2),
    DUE_DATE           DATE,
    PAID_DATETIME      TIMESTAMP_NTZ,
    AMOUNT_DUE_ZAR     NUMBER(12,2),
    AMOUNT_PAID_ZAR    NUMBER(12,2),
    PAYMENT_STATUS     VARCHAR(20),
    DAYS_PAST_DUE      NUMBER(4),
    _LOADED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACT_INSURANCE_POLICY (
    POLICY_ID                VARCHAR(20) NOT NULL PRIMARY KEY,
    CUSTOMER_ID              VARCHAR(20),
    BUSINESS_KEY             VARCHAR(10),
    PRODUCT_NAME             VARCHAR(50),
    PLAN_NAME                VARCHAR(30),
    MONTHLY_PREMIUM_ZAR      NUMBER(10,2),
    COVER_AMOUNT_ZAR         NUMBER(14,2),
    POLICY_START_DATE        DATE,
    POLICY_STATUS            VARCHAR(20),
    TOTAL_PREMIUMS_PAID_ZAR  NUMBER(14,2),
    BENEFICIARY_NAME         VARCHAR(100),
    REPATRIATION_COUNTRY     VARCHAR(5),
    _LOADED_AT               TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS FACT_INSURANCE_CLAIM (
    CLAIM_ID            VARCHAR(20) NOT NULL PRIMARY KEY,
    POLICY_ID           VARCHAR(20),
    CUSTOMER_ID         VARCHAR(20),
    BUSINESS_KEY        VARCHAR(10),
    CLAIM_DATETIME      TIMESTAMP_NTZ,
    DATE_KEY            NUMBER,
    CLAIM_TYPE          VARCHAR(30),
    CLAIMED_AMOUNT_ZAR  NUMBER(14,2),
    DECISION            VARCHAR(20),
    PAID_AMOUNT_ZAR     NUMBER(14,2),
    TURNAROUND_DAYS     NUMBER(3),
    REPUDIATION_REASON  VARCHAR(50),
    _LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ── MAMA MONEY EXTENSION ──────────────────────────────────────
CREATE TABLE IF NOT EXISTS FACT_USD_SAVINGS (
    SAVINGS_ID              VARCHAR(20) NOT NULL PRIMARY KEY,
    CUSTOMER_ID             VARCHAR(20),
    BUSINESS_KEY            VARCHAR(10),
    ACCOUNT_OPENED_DATE     DATE,
    ACCOUNT_STATUS          VARCHAR(20),
    CURRENT_BALANCE_USDC    NUMBER(16,4),
    CURRENT_BALANCE_USD     NUMBER(16,2),
    CURRENT_BALANCE_ZAR     NUMBER(16,2),
    TOTAL_PURCHASED_USDC    NUMBER(16,4),
    TOTAL_SOLD_USDC         NUMBER(16,4),
    LAST_PURCHASE_DATE      DATE,
    UNDERLYING_ASSET        VARCHAR(10),
    IS_USDC_BACKED          BOOLEAN,
    _LOADED_AT              TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Mama Money USDC-backed USD savings. NOT a standard bank account.';

SELECT 'Bronze DDL complete — ' || COUNT(*) || ' tables created'
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'BRONZE' AND TABLE_CATALOG = 'AFRIMONEY_DB';
