-- ============================================================
-- AfriMoney Intelligence Platform
-- Bronze Layer ETL — COPY INTO from internal stage
-- Step 3 of 6: Run after uploading CSVs to AFRIMONEY_STAGE
-- ============================================================
-- HOW TO UPLOAD:
--   snowsql -a <account> -u <user> -d AFRIMONEY_DB -s STAGING
--   PUT file://C:\AfriMoney\data\bronze\dim_customer.csv @AFRIMONEY_STAGE/dim_customer/ AUTO_COMPRESS=TRUE;
--
-- Or use SnowSQL bulk upload script below.

USE ROLE AFRIMONEY_ENG;
USE WAREHOUSE AFRIMONEY_INGEST_WH;
USE DATABASE AFRIMONEY_DB;
USE SCHEMA BRONZE;

-- ── Helper: create a reusable CSV file format ─────────────────
CREATE OR REPLACE FILE FORMAT AFRIMONEY_CSV_FORMAT
    TYPE               = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER        = 1
    NULL_IF            = ('NULL','null','','N/A','None')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT        = 'AUTO'
    TIMESTAMP_FORMAT   = 'AUTO'
    COMPRESSION        = 'AUTO';

-- ── DIM_BUSINESS ──────────────────────────────────────────────
COPY INTO BRONZE.DIM_BUSINESS (
    BUSINESS_SK, BUSINESS_KEY, BUSINESS_NAME, FOUNDED_YEAR, HQ_COUNTRY, PRIMARY_CURRENCY, BRAND_COLOUR
)
FROM @STAGING.AFRIMONEY_STAGE/dim_business/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT'
PURGE = FALSE;

-- ── DIM_DATE ──────────────────────────────────────────────────
COPY INTO BRONZE.DIM_DATE
FROM @STAGING.AFRIMONEY_STAGE/dim_date/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

-- ── DIM_CUSTOMER (500K rows — expect ~30-60s on MEDIUM WH) ───
COPY INTO BRONZE.DIM_CUSTOMER (
    CUSTOMER_SK, CUSTOMER_ID, BUSINESS_KEY, FIRST_NAME, LAST_NAME,
    DATE_OF_BIRTH, AGE_YEARS, GENDER, NATIONALITY, RESIDENCE_COUNTRY,
    PREFERRED_LANGUAGE, MOBILE_NUMBER_TOKEN, EMAIL_HASH,
    REGISTRATION_DATETIME, REGISTRATION_CHANNEL, KYC_LEVEL,
    KYC_COMPLETED_DATE, CUSTOMER_STATUS, RISK_BAND, CUSTOMER_SEGMENT,
    MONTHLY_INCOME_BAND, EMPLOYER_TYPE, HAS_SA_ID, HAS_PASSPORT,
    IS_MARKETING_OPT_IN, ACQUISITION_SOURCE, SCD_VERSION, SCD_START_DATE,
    SCD_END_DATE, IS_CURRENT
)
FROM @STAGING.AFRIMONEY_STAGE/dim_customer/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

-- ── DIM_RECIPIENT (1M rows) ───────────────────────────────────
COPY INTO BRONZE.DIM_RECIPIENT
FROM @STAGING.AFRIMONEY_STAGE/dim_recipient/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

-- ── FACT_FX_RATE ──────────────────────────────────────────────
COPY INTO BRONZE.FACT_FX_RATE
FROM @STAGING.AFRIMONEY_STAGE/fact_fx_rate/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

-- ── FACT_REMITTANCE_TRANSFER (5M rows — use LARGE WH) ────────
-- Switch to larger WH for this load
USE WAREHOUSE AFRIMONEY_TRANSFORM_WH;
COPY INTO BRONZE.FACT_REMITTANCE_TRANSFER
FROM @STAGING.AFRIMONEY_STAGE/fact_remittance_transfer/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT'
PURGE = FALSE;

-- ── FACT_TRANSFER_STATUS_HISTORY ──────────────────────────────
COPY INTO BRONZE.FACT_TRANSFER_STATUS_HISTORY (
    TRANSFER_ID, BUSINESS_KEY, STATUS_CODE, STATUS_DATETIME, DATE_KEY,
    ELAPSED_MINUTES_FROM_CREATED, SYSTEM_USER, NOTES
)
FROM @STAGING.AFRIMONEY_STAGE/fact_transfer_status_history/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

-- ── FACT_PAYMENT ──────────────────────────────────────────────
COPY INTO BRONZE.FACT_PAYMENT
FROM @STAGING.AFRIMONEY_STAGE/fact_payment/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

-- ── FACT_PAYOUT ───────────────────────────────────────────────
COPY INTO BRONZE.FACT_PAYOUT
FROM @STAGING.AFRIMONEY_STAGE/fact_payout/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

-- ── FACT_WALLET_LEDGER ────────────────────────────────────────
COPY INTO BRONZE.FACT_WALLET_LEDGER
FROM @STAGING.AFRIMONEY_STAGE/fact_wallet_ledger/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

-- ── FACT_CARD_TRANSACTION ─────────────────────────────────────
COPY INTO BRONZE.FACT_CARD_TRANSACTION
FROM @STAGING.AFRIMONEY_STAGE/fact_card_transaction/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

-- ── Mukuru extensions ─────────────────────────────────────────
COPY INTO BRONZE.FACT_LOAN_APPLICATION
FROM @STAGING.AFRIMONEY_STAGE/fact_loan_application/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO BRONZE.FACT_LOAN_REPAYMENT
FROM @STAGING.AFRIMONEY_STAGE/fact_loan_repayment/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO BRONZE.FACT_INSURANCE_POLICY
FROM @STAGING.AFRIMONEY_STAGE/fact_insurance_policy/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO BRONZE.FACT_INSURANCE_CLAIM
FROM @STAGING.AFRIMONEY_STAGE/fact_insurance_claim/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO BRONZE.FACT_USD_SAVINGS
FROM @STAGING.AFRIMONEY_STAGE/fact_usd_savings/
FILE_FORMAT = (FORMAT_NAME = 'AFRIMONEY_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

-- ── Load verification ────────────────────────────────────────
SELECT
    TABLE_NAME,
    ROW_COUNT,
    BYTES / 1024 / 1024 AS SIZE_MB,
    LAST_ALTERED
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'BRONZE'
ORDER BY ROW_COUNT DESC NULLS LAST;

-- ── COPY_HISTORY audit ───────────────────────────────────────
SELECT
    TABLE_NAME,
    STATUS,
    ROW_COUNT,
    ROWS_LOADED,
    ERRORS_SEEN,
    FIRST_ERROR_MESSAGE,
    LAST_LOAD_TIME
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
    TABLE_NAME => 'FACT_REMITTANCE_TRANSFER',
    START_TIME => DATEADD(HOURS, -2, CURRENT_TIMESTAMP())
))
ORDER BY LAST_LOAD_TIME DESC;
